name: python任务

on:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]
jobs:
  build:
    env:
      BARK: ${{ secrets.BARK }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requirements'
        run: pip install -r ./workflow/requirements.txt


      - name: '运行【喜马拉雅极速版】'
        run: python3 ./workflow/xmly_speed.py
        env:
          TZ: Asia/shanghai
          XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}


      - name: '运行【中青任务】'
        run: python3 workflow/youth.py
        env:
          YOUTH_HEADER1: ${{ secrets.YOUTH_HEADER1 }}  #必须 账号1 body1
          YOUTH_READBODY1: ${{ secrets.YOUTH_READBODY1 }}  #必须 账号1 body1
          YOUTH_REDBODY1: ${{ secrets.YOUTH_REDBODY1 }}  #必须 账号1 body1
          YOUTH_READTIMEBODY1: ${{ secrets.YOUTH_READTIMEBODY1 }}  #必须 账号1 body1
          YOUTH_WITHDRAWBODY1: ${{ secrets.YOUTH_READTIMEBODY1 }}  #非必须 账号1提现 body1
          YOUTH_SHAREBODY1: ${{ secrets.YOUTH_SHAREBODY1 }}  #非必须 账号1分享 body1
          YOUTH_HEADER2: ${{ secrets.YOUTH_HEADER2 }}  #非必须 账号2 body2
          YOUTH_READBODY2: ${{ secrets.YOUTH_READBODY2 }}  #非必须 账号2 body2
          YOUTH_REDBODY2: ${{ secrets.YOUTH_REDBODY2 }}  #非必须 账号2 body2
          YOUTH_READTIMEBODY2: ${{ secrets.YOUTH_READTIMEBODY2 }}  #非必须 账号2 body2
          YOUTH_WITHDRAWBODY2: ${{ secrets.YOUTH_READTIMEBODY2 }}  #非必须 账号2提现 body2
          YOUTH_SHAREBODY2: ${{ secrets.YOUTH_SHAREBODY2 }}  #非必须 账号2分享 body2