# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QQ阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '*/11 23,0-15 * * *'
  watch:
    types: started
env:
    TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQreadurlVal: ${{ secrets.QQ_QQreadURL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.QQ_QQreadURL
        run: |
          npm install
      - name: '运行 【QQ阅读】'
        if: env.QQ_QQreadURL
        run: |
          node workflow/QQread.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK: ${{ secrets.BARK }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
