name: 云扫码


on:
  workflow_dispatch:
  schedule:
     - cron: '3 1-14 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YSM_URL: ${{ secrets.YSM_URL }}
        YSM_HD: ${{ secrets.YSM_HD }}    
        YSM_BD: ${{ secrets.YSM_BD }} 
        YSM2_BD: ${{ secrets.YSM2_BD }}   
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【云扫码】'
        if: env.YSM_HD
        run: |
          node workflow/ysm1.js
        env:
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
