name: 腾讯自选股养牛

on:
    workflow_dispatch:
    schedule:
        - cron: "30 8 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【腾讯自选股养牛】"
              run: |
                  node workflow/TencentStockCow.js
              env:
                  userheaderVal: ${{ secrets.USERHEADERVAL }}
                  userkeyVal: ${{ secrets.USERKEYVAL }}
                  signheaderVal: ${{ secrets.SIGNHEADERVAL }}
                  signkeyVal: ${{ secrets.SIGNKEYVAL }}
                  taskheaderVal: ${{ secrets.TASKHEADERVAL }}
                  taskkeyVal: ${{ secrets.TASKKEYVAL }}
                  wxtaskkeyVal: ${{ secrets.WXTASKKEYVAL }}
                  cashheaderVal: ${{ secrets.CASHHEADERVAL }}
                  cowkeyVal: ${{ secrets.COWKEYVAL }}
                  

                  
